version: '3.7'

services:

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports: 
            - 8000:80
        environment:
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - db

    db:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root

    wordpress:
        container_name: wordpress
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - 80:80
            - 443:443
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: root
            WORDPRESS_DB_NAME: test
        working_dir: /var/www/html
        volumes:
            - ./wordpress:/var/www/html
volumes:
    db_data: 
  